name: 'Deployment changed app'

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  NODE_VERSION: 18

jobs:
  deployment-with-turbo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: typescript-turbo
    steps:
    - uses: actions/checkout@v3
    - name: cache node_modules
      id: node_modules_cache_id
      uses: actions/cache@v3
      with:
        key: node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles('**/package-lock.json') }}
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: install node modules
      if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
      run: npm ci
    - name: deployment
      run: npx turbo run deploy:dev --filter=\[origin/main...$(git branch --show-current)\]