name: Create release pull request

on:
  push:
    branch:
      - main
    paths:
      - .changeset/**.md

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: cache node_modules
      #   id: node_modules_cache_id
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.npm
      #     key: node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       node-v${{ env.NODE_VERSION }}-deps-
      #       node-v${{ env.NODE_VERSION }}-
      #       node-v

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install node modules
        # if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}