name: 'Tag push test'

on:
  push:
    branches:
      - main

jobs:
  push-tag:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: typescript-turbo

    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install node modules
        run: npm ci

      - name: create tag
        run: npx changeset tag

      - name: check tag
        run: git tag

      - name: check tag 2
        run: git tag foo && git tag

      # - name: push tag
      #   run: git push origin --tags